import airline1 from '@/app/assets/Airlines3.svg'
import airline2 from '@/app/assets/Airlines4.svg'
import airline3 from '@/app/assets/DeltaAirlines.svg'
import airline4 from '@/app/assets/UnitedAirlines.svg'


export const departingflights = [
    {
        "id": 1,
        "image": airline1,
        "time": "16h 45m",
        "Airline": "Hawaiian Airlines",
        "timerange": "7:00 AM - 4:15 PM",
        "stops": "1 stop",
        "loc": "2h 45m in HNL",
        "price": "$624",
        "triptype": "round trip",
        "flightno" : "AI 201",
        "aircrafttype" : "Boeing 777",
        "departure" : "DEL - New Delhi,India",
        "arrival" : "JFK - New York,USA",
        "departterminal" : "Terminal 1",
        "arrterminal" : "Terminal 3"
    },
    {
        "id": 2,
        "image": airline2,
        "time": "18h 22m",
        "Airline": "Japan Airlines",
        "timerange": "7:35 AM - 12:15 PM",
        "stops": "1 stop",
        "loc": "50m in HKG",
        "price": "$663",
        "triptype": "round trip",
        "flightno" : "AI 202",
        "aircrafttype" : "Boeing 778",
        "departure" : "BOM - Mumbai,India",
        "arrival" : "LAX - Los Angeles,USA",
        "departterminal" : "Terminal 2",
        "arrterminal" : "Terminal 1"
    },
    {
        "id": 3,
        "image": airline1,
        "time": "18h 04m",
        "Airline": "Japan Airlines",
        "timerange": "8:20 AM - 2:15 PM",
        "stops": "1 stop",
        "loc": "1h 50m in PVG",
        "price": "$690",
        "triptype": "round trip",
        "flightno" : "AI 203",
        "aircrafttype" : "Boeing 779",
        "departure" : "JFK - New York,USA",
        "arrival" : "DOH – Doha,Qatar",
        "departterminal" : "Terminal 3",
        "arrterminal" : "Terminal 2"
    },
    {
        "id": 4,
        "image": airline3,
        "time": "18h 04m",
        "Airline": "Delta",
        "timerange": "9:47 AM - 4:15 PM",
        "stops": "1 stop",
        "loc": "4h 05m in ICN",
        "price": "$756",
        "triptype": "round trip",
        "flightno" : "AI 204",
        "aircrafttype" : "Boeing 780",
        "departure" : "HKG – Hong Kong",
        "arrival" : "IST – Istanbul,Turkey",
        "departterminal" : "Terminal 1",
        "arrterminal" : "Terminal 3"
    },
    {
        "id": 5,
        "image": airline4,
        "time": "18h 04m",
        "Airline": "Hawaiian Airlines",
        "timerange": "11:15 AM - 7:45 PM",
        "stops": "Nonstop",
        "loc": "",
        "price": "$837",
        "triptype": "round trip",
        "flightno" : "AI 205",
        "aircrafttype" : "Boeing 781",
        "departure" : "YYZ – Toronto,Canada",
        "arrival" : "DOH – Doha,Qatar",
        "departterminal" : "Terminal 1",
        "arrterminal" : "Terminal 4"
    },
    {
        "id": 6,
        "image": airline2,
        "time": "18h 22m",
        "Airline": "Japan Airlines",
        "timerange": "7:35 AM - 12:15 PM",
        "stops": "1 stop",
        "loc": "50m in HKG",
        "price": "$663",
        "triptype": "round trip",
        "flightno" : "AI 206",
        "aircrafttype" : "Boeing 782",
        "departure" : "JFK – New York, USA",
        "arrival" : "DOH – Doha,Qatar",
        "departterminal" : "Terminal 2",
        "arrterminal" : "Terminal 4"
    },
    {
        "id": 7,
        "image": airline1,
        "time": "16h 45m",
        "Airline": "Hawaiian Airlines",
        "timerange": "7:00 AM - 4:15 PM",
        "stops": "1 stop",
        "loc": "2h 45m in HNL",
        "price": "$624",
        "triptype": "round trip",
        "flightno" : "AI 207",
        "aircrafttype" : "Boeing 783",
        "departure" : "BLR – Bengaluru",
        "arrival" : "COK – Kochi",
        "departterminal" : "Terminal 3",
        "arrterminal" : "Terminal 1"
    },
    {
        "id": 8,
        "image": airline2,
        "time": "18h 22m",
        "Airline": "Japan Airlines",
        "timerange": "7:35 AM - 12:15 PM",
        "stops": "1 stop",
        "loc": "50m in HKG",
        "price": "$663",
        "triptype": "round trip",
        "flightno" : "AI 208",
        "aircrafttype" : "Boeing 784",
        "departure" : "PAT – Patna",
        "arrival" : "AMD – Ahmedabad",
        "departterminal" : "Terminal 5",
        "arrterminal" : "Terminal 2"
    },
    {
        "id": 9,
        "image": airline1,
        "time": "18h 04m",
        "Airline": "Japan Airlines",
        "timerange": "8:20 AM - 2:15 PM",
        "stops": "1 stop",
        "loc": "1h 50m in PVG",
        "price": "$690",
        "triptype": "round trip",
        "flightno" : "AI 209",
        "aircrafttype" : "Boeing 785",
        "departure" : "IXC – Chandigarh",
        "arrival" : "TRV – Thiruvananthapuram",
        "departterminal" : "Terminal 6",
        "arrterminal" : "Terminal 2"
    },
    {
        "id": 10,
        "image": airline3,
        "time": "18h 04m",
        "Airline": "Delta",
        "timerange": "9:47 AM - 4:15 PM",
        "stops": "1 stop",
        "loc": "4h 05m in ICN",
        "price": "$756",
        "triptype": "round trip",
        "flightno" : "AI 210",
        "aircrafttype" : "Boeing 786",
        "departure" : "IXC – Chandigarh",
        "arrival" : "MAA – Chennai",
        "departterminal" : "Terminal 1",
        "arrterminal" : "Terminal 2"
    },
    {
        "id": 11,
        "image": airline4,
        "time": "18h 04m",
        "Airline": "Hawaiian Airlines",
        "timerange": "11:15 AM - 7:45 PM",
        "stops": "Nonstop",
        "loc": "",
        "price": "$837",
        "triptype": "round trip",
        "flightno" : "AI 211",
        "aircrafttype" : "Boeing 787",
        "departure" : "IXC – Chandigarh",
        "arrival" : "DEL – New Delhi",
        "departterminal" : "Terminal 5",
        "arrterminal" : "Terminal 2"
    },
    {
        "id": 12,
        "image": airline2,
        "time": "18h 22m",
        "Airline": "Japan Airlines",
        "timerange": "7:35 AM - 12:15 PM",
        "stops": "1 stop",
        "loc": "50m in HKG",
        "price": "$663",
        "triptype": "round trip",
        "flightno" : "AI 212",
        "aircrafttype" : "Boeing 788",
        "departure" : "BLR – Bengaluru",
        "arrival" : "LAX – Los Angeles, USA",
        "departterminal" : "Terminal 3",
        "arrterminal" : "Terminal 2"
    }
]